language: node_js
node_js:
- '8'
script:
- npm run build
- npm run test-coverage
- npm run codecov
- git checkout package-lock.json

cache:
  directories:
    - node_modules

install:
  - npm install

deploy:
  provider: script
  script: './deploy_dockerhub.sh'
  on:
    branch: master

